name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Python ortamını ayarla
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Testleri çalıştır
        run: pytest

